//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrador
    {
        public int id { get; set; }
        public string correo { get; set; }
        public string contraseña { get; set; }
        public int estado { get; set; }
        public int ID_TIPO_USUARIO { get; set; }
        public string estado_String { get; set; }

        public virtual Tipo_Usuario Tipo_Usuario { get; set; }
    }
}
