//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMEP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class AgendaCita
    {
        [Key]
        public int id { get; set; }

        [Display(Name = "Hora")]
        [Required(ErrorMessage = "Seleccione la hora")]
        public int idHora { get; set; }

        [Column(TypeName = "text")]
        [Display(Name = "Descripción")]
        [DataType(DataType.MultilineText)]
        public string detalle { get; set; }

        [Display(Name = "Hora")]
        public virtual Horario Horario { get; set; }
    }
}
