//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgendaCita
    {
        public int id { get; set; }
        public int idHora { get; set; }
        public string detalle { get; set; }
    
        public virtual Horario Horario { get; set; }
    }
}
