//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMEP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Alcohol
    {
        [Key]
        public int id { get; set; }
        [Display(Name = "Estado")]
        [Required(ErrorMessage = "Seleccione el estado")]
        public int activo { get; set; }
        [Display(Name = "Inicio")]
        [Required(ErrorMessage = "Digite la edad  de inicio")]
        public int inicio { get; set; }
        [Display(Name = "Frecuencia")]
        [Required(ErrorMessage = "Digite la frecuencia de tomado")]
        public int frecuencia { get; set; }

        [Display(Name = "Tipo")]
        [Required(ErrorMessage = "Seleccione el tipo de bebida")]
        public string tipo { get; set; }

        public int cant_tipo { get; set; }

        [Column(TypeName = "text")]
        [Display(Name = "Observaciones")]
        [DataType(DataType.MultilineText)]
        public string observaciones { get; set; }
        [Display(Name = "Expediente")]
        [Required(ErrorMessage = "Seleccione el Expediente")]
        public int ID_EXPEDIENTE { get; set; }

        [Display(Name = "Expediente")]
        public virtual Expediente Expediente { get; set; }
    }
}
