
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EMEP.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Compartir_Expediente
{

    public int id { get; set; }

    public int ID_EXPEDIENTE { get; set; }

    public string ID_PACIENTE { get; set; }

    public int estado { get; set; }

    public string ID_PACIENTE_COMPARTE { get; set; }



    public virtual Paciente Paciente { get; set; }

}

}
