//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compartir_Expediente
    {
        public int id { get; set; }
        public int ID_EXPEDIENTE { get; set; }
        public string ID_PACIENTE { get; set; }
        public int estado { get; set; }
        public string ID_PACIENTE_COMPARTE { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
