//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datos_Paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Datos_Paciente()
        {
            this.Paciente_Paciente_Asociado = new HashSet<Paciente_Paciente_Asociado>();
        }
    
        public int id { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string tipo_sangre { get; set; }
        public string recidencia { get; set; }
        public string telefono { get; set; }
        public string contacto_emergencia { get; set; }
        public string parentesco { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paciente_Paciente_Asociado> Paciente_Paciente_Asociado { get; set; }
    }
}
