//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMEP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Enfermedad_Familiar
    {
        [Key]
        public int id { get; set; }
        [Display(Name = "Enfermedad")]
        [Required(ErrorMessage = "Seleccione la enfermedad")]
        public int ID_ENFERMEDAD { get; set; }
        [Display(Name = "Expediente")]
        [Required(ErrorMessage = "Seleccione el expediente")]
        public int ID_EXPEDIENTE { get; set; }
        [Display(Name = "Expediente")]
        public virtual Expediente Expediente { get; set; }
        [Display(Name = "Enfermedad")]
        public virtual Lista_Enfermedad Lista_Enfermedad { get; set; }
    }
}
