//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enfermedad_Expediente
    {
        public int id { get; set; }
        public int ID_EFERMEDAD { get; set; }
        public int ID_EXPEDIENTE { get; set; }
    
        public virtual Expediente Expediente { get; set; }
        public virtual Lista_Enfermedad Lista_Enfermedad { get; set; }
    }
}
