//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMEP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Enfermedad_Expediente
    {
        [Key]
        public int id { get; set; }
        [Display(Name = "Enfermedad")]
        [Required(ErrorMessage = "Seleccione la enfermedad")]
        public int ID_EFERMEDAD { get; set; }
        [Display(Name = "Expediente")]
        [Required(ErrorMessage = "Seleccione el expediente")]
        public int ID_EXPEDIENTE { get; set; }
        [Display(Name = "Expediente")]
        public virtual Expediente Expediente { get; set; }
        [Display(Name = "Enfermedad")]
        public virtual Lista_Enfermedad Lista_Enfermedad { get; set; }
    }
}
