//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMEP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Expediente_Alergia
    {
        [Key]
        public int id { get; set; }

        [Display(Name = "Expediente")]
        [Required(ErrorMessage = "Seleccione el Expediente")]
        public int ID_EXPEDIENTE { get; set; }
        [Display(Name = "Alergia")]
        [Required(ErrorMessage = "Seleccione la Alergia")]
        public int ID_ALERGIA { get; set; }

        [Display(Name = "Expediente")]
        public virtual Expediente Expediente { get; set; }
        [Display(Name = "Alergia")]
        public virtual Lista_Alergia Lista_Alergia { get; set; }
    }
}
