//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expediente_Alergia
    {
        public int id { get; set; }
        public int ID_EXPEDIENTE { get; set; }
        public int ID_ALERGIA { get; set; }
    
        public virtual Expediente Expediente { get; set; }
        public virtual Lista_Alergia Lista_Alergia { get; set; }
    }
}
