//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMEP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ListaCita
    {
        [Key]
        public int id { get; set; }
        [Display(Name = "Registro de citas")]
        [Required(ErrorMessage = "Seleccione un registro de citas")]
        public int idRegistrarCita { get; set; }
        [Display(Name = "Registro de citas")]
        public virtual RegistrarCita RegistrarCita { get; set; }

    }
}
