//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMEP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EMEPEntities : DbContext
    {
        public EMEPEntities()
            : base("name=EMEPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrador> Administrador { get; set; }
        public virtual DbSet<AgendaCita> AgendaCita { get; set; }
        public virtual DbSet<Alcohol> Alcohol { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Categoria_Alergia> Categoria_Alergia { get; set; }
        public virtual DbSet<Cirugia> Cirugia { get; set; }
        public virtual DbSet<Compartir_Expediente> Compartir_Expediente { get; set; }
        public virtual DbSet<Consulta> Consulta { get; set; }
        public virtual DbSet<Consultorio> Consultorio { get; set; }
        public virtual DbSet<Enfermedad_Expediente> Enfermedad_Expediente { get; set; }
        public virtual DbSet<Enfermedad_Familiar> Enfermedad_Familiar { get; set; }
        public virtual DbSet<Especialidad> Especialidad { get; set; }
        public virtual DbSet<Expediente> Expediente { get; set; }
        public virtual DbSet<Expediente_Alergia> Expediente_Alergia { get; set; }
        public virtual DbSet<Fumador> Fumador { get; set; }
        public virtual DbSet<Horario> Horario { get; set; }
        public virtual DbSet<Lista_Actividad_Fisica> Lista_Actividad_Fisica { get; set; }
        public virtual DbSet<Lista_Alergia> Lista_Alergia { get; set; }
        public virtual DbSet<Lista_Enfermedad> Lista_Enfermedad { get; set; }
        public virtual DbSet<ListaCita> ListaCita { get; set; }
        public virtual DbSet<Medicamento> Medicamento { get; set; }
        public virtual DbSet<Medico> Medico { get; set; }
        public virtual DbSet<Otra_Actividad> Otra_Actividad { get; set; }
        public virtual DbSet<Otra_Alergia> Otra_Alergia { get; set; }
        public virtual DbSet<Otra_Enfermedad> Otra_Enfermedad { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
        public virtual DbSet<Paciente_Asociado> Paciente_Asociado { get; set; }
        public virtual DbSet<Paciente_Dueño_Asociado> Paciente_Dueño_Asociado { get; set; }
        public virtual DbSet<RegistrarCita> RegistrarCita { get; set; }
        public virtual DbSet<Tipo_Usuario> Tipo_Usuario { get; set; }
    }
}
