//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMEP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Otra_Alergia
    {
        [Key]
        public int id { get; set; }
        [Display(Name = "Nombre")]
        [Required(ErrorMessage = "Debe de escribir el nombre")]
        public string descripcion { get; set; }
        public bool estad { get; set; }
        public int estado { get; set; }
        [Display(Name = "Estado")]
        [Required(ErrorMessage = "Seleccione el estado")]
        public string estado_String { get; set; }

        [Display(Name = "Reacción")]
        [Required(ErrorMessage = "Debe de escribir la reacción")]
        public string reaccion { get; set; }
        [Column(TypeName = "text")]
        [Display(Name = "Observaciones")]
        [DataType(DataType.MultilineText)]
        public string observaciones { get; set; }

        [DataType(DataType.ImageUrl)]
        [Display(Name = "Imagen")]
        [Required(ErrorMessage = "Seleccione imegen")]
        public byte[] img { get; set; }

        [Display(Name = "Expediente")]
        [Required(ErrorMessage = "Seleccione el expediente")]
        public int ID_EXPEDIENTE { get; set; }
        [Display(Name = "Categoria")]
        [Required(ErrorMessage = "Seleccione la categoria")]
        public int ID_CATEGORIA { get; set; }
        [Display(Name = "Expediente")]
        public virtual Expediente Expediente { get; set; }
    }
}
