//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otra_Alergia
    {
        public int id { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> estado { get; set; }
        public string reaccion { get; set; }
        public string observaciones { get; set; }
        public string img { get; set; }
        public Nullable<int> ID_EXPEDIENTE { get; set; }
        public Nullable<int> ID_CATEGORIA { get; set; }
    
        public virtual Expediente Expediente { get; set; }
    }
}
