//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otra_Alergia
    {
        public int id { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> estado { get; set; }
        public string reaccion { get; set; }
        public string observaciones { get; set; }
        public string img { get; set; }
        public Nullable<int> ID_EXPEDIENTE { get; set; }
        public Nullable<int> ID_CATEGORIA { get; set; }
    
        public virtual Expediente Expediente { get; set; }
    }
}
