//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMEP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Paciente_Dueño_Asociado
    {
        [Key]
        public int id { get; set; }
        [Display(Name = "Paciente dueño")]
        [Required(ErrorMessage = "Seleccione el paciente dueño")]
        public string ID_PACIENTE_DUE { get; set; }
        [Display(Name = "Paciente asociado")]
        [Required(ErrorMessage = "Seleccione el paciente asociado")]
        public string ID_PACIENTE_ASO { get; set; }

        [Display(Name = "Paciente dueño")]
        public virtual Paciente Paciente { get; set; }
        [Display(Name = "Paciente asociado")]
        public virtual Paciente_Asociado Paciente_Asociado { get; set; }
    }
}
