//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente_Dueño_Asociado
    {
        public int id { get; set; }
        public string ID_PACIENTE_DUE { get; set; }
        public string ID_PACIENTE_ASO { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        public virtual Paciente_Asociado Paciente_Asociado { get; set; }
    }
}
