//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMEP.Models
{
    using System;
    using System.Collections;
    using System.Collections.Generic;

    public partial class Paciente_Paciente_Asociado
    {
        public string ID_PACIENTE { get; set; }
        public int ID_PACIENTE_ASOCIADO { get; set; }
        public int id { get; set; }

        public Paciente paciente { get; set; }
        public Datos_Paciente datosPaciente { get; set; }

       public static List<Paciente> listaPaciente1 { get; set; }
        public static List<Datos_Paciente> listaDatos1 { get; set; }

  public List<Paciente_Paciente_Asociado> listaAsociado { get; set; }


        public virtual Datos_Paciente Datos_Paciente { get; set; }
        public virtual Paciente Paciente { get; set; }

       


    }
}
